### ISSUE TITLE
Cant find apex_application_settings

### ISSUE THREAD

**Issue by neilfernandez** [Dani3lSun/apex-plugin-analytics#1]
Hi Daniel,

It looks like the script can not find the apex_application_settings table/view, and neither can I. Tried searching and can not find anything resembling this. Any advice on where in my schema this should be or if this is referring to the wrong table?

Best,
Neil

**Comment by neilfernandez** [comment]
Realized that this is only in APEX 18 and up. Is there a version of the plugin compatible with APEX 5.1? Seems like there are a few dependencies in here for that APEX setting table.

**Comment by Dani3lSun** [comment]
Hey @neilfernandez 
There are 2 sides, the plugin itself is supported on APEX env >= 5.1, but the management app is only available for APEX 18.x
